### ISSUE TITLE
Make a document with all programs needed to run this app.

### ISSUE THREAD

**Issue by juanpablomaggi** [SepaSoporteIt/SEPA_APP_REACT#12]
Make a document with all needed programs to run this app for development and deployment.

**Comment by FrancoAltavilla** [comment]
### Instalación con NPM
1- InstalarJava 11, se peude descargar de [AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot).

2- Instalar [Node.js](https://nodejs.org/en/), verificar que sea una version LTS ya que otras no son soportadas.

3- Abrir PowerShell o la terminal de node.js y ejecutar el comando 

> **npm install -g generator-jhipster**


4- Luego de la instalación ejecutar el comando **gradlew** en windows o **gradle** en otros sistemas. este ultimo comando se utiliza cada vez que sea necesario iniciar la aplicación.

Opcionalmente se puede instalar Yeoman utilizando el siguiente comando en la consola de node.js o PoweShell 

> npm install -g yo
