### ISSUE TITLE
Internalization

### ISSUE THREAD

**Issue by juanpablomaggi** [SepaSoporteIt/SEPA_APP_REACT#3]
Make the localization for the company, study, expiration and employee entities

**Comment by juanpablomaggi** [comment]
As a comment, the localization folder is located at src/main/webapp/i18n

(there's two folders in there, one for english and one for spanish)

**Comment by juanpablomaggi** [comment]
Add to the list industryType entity and the global code (has the name of the entities as well)

**Comment by AlanGDC** [comment]
Se creo branch ```issues_3_Internalization/Audits_Company_Employye_Expiration```

**Comment by juanpablomaggi** [comment]
First internalization PR approved and merged to master.
