### ISSUE TITLE
Investigation - Database migration

### ISSUE THREAD

**Issue by juanpablomaggi** [SepaSoporteIt/SEPA_APP_REACT#5]
Make an investigation about how to migrate the actual DB to the new DB. We can use the DB tool included on the app.

**Comment by FrancoAltavilla** [comment]
Expiration: falta agregar los campos "codigounico" y "responsable" ambos string
Company: ver la utilidad de "solicitadorId", "abitoId" , "autoridadId", "legislacionId" , "frecuencyTypeId" y falta agregar "companyType" ( string)
